SELECT
    id AS profile_id,
    account_id AS profile_name,
    nickname,
    biography,
    url AS profile_url,
    TRY_TO_NUMBER(followers) AS num_followers,
    TRY_TO_NUMBER(following_) AS num_following,
    TRY_TO_NUMBER(likes) AS likes,
    TRY_TO_NUMBER(videos_count) AS videos_count,
    TRY_TO_TIMESTAMP_NTZ(create_time) AS profile_created_at,
    is_verified,
    is_private,
    is_ad_virtual,
    region,
    awg_engagement_rate as avg_engagement_rate,
    comment_engagement_rate,
    like_engagement_rate,
FROM {{ source('raw_tiktok', 'profiles') }}
WHERE id IS NOT NULL